### ISSUE TITLE
type errors in node env

### ISSUE THREAD

**Issue by salmin89** [guest271314/native-messaging-typescript#1]
Hey,
is this example giving you errors in TS 5.5 or am I missing any type declarations?

Replicated in sandbox: [typescriptlang.org](https://www.typescriptlang.org/play/?target=99#code/PTAEBUE8AcFMGUDGAnAltALqAcgQw6gG6ygCysAzhbgOaoB2NoAFgPYUYCwAUCKDQFdKGAEwB2AIwBmCQBYANKDEBaEQA5VABhGyewAFQ8AxAEJgAismAAjBsFj1CoZfFDA2AW1jmKsK7fpgABMHVlBkAXpjMwt-OwcnFzdPbws-GztrSPDs6J84wITnV3dWLx90gOB6VhDnZVgADzg0L3oMXAAbZRCAM1wBToxlDBhYAF4PWsGSZQbmv1Q2ju6ONGgRsYoefWAeUDd9Q24D-Tc+AB5kWF6-B0QSUbgKcYAiZgwMaAoALhBkXAAdwAdHQMMwBFlfMhEKx2g4MMDYR5gB5UCh2KxehhgFA4Eh1jjYDdekERJoAJwSACssmsEhEIiCdIpQU0sFwiFwslk1JEADZcOI1LJNGIpLhvJZEMBOqhrPYKOSdMDcMgAZAsr1bshgUFgRgKK83AA+fagXY8BgYPz9B6gACC6twkAAQgJtX5QABvc0GY4HC2gACSvVA4NQFEdzrdHp1oEj4UoqAAXrhrJ1YIprhgBMh6FHwSQPLhGksBB5QNZIDbQJnGOD+EQHKAgnmGExYQWMBFEAQ4QBuJO5-OF5gkau1+s0RuoMM1RHmi1Ls4AbVIABFsABdAAUHy+vxAIWInVYLWBUxTqE6nVwwNYyBowVYiAowAA6rAFQApXCEXACXQHEACUbjuegHmAABxM9rC6AB9AB5awACtYD7d8nQ1d1PSsEtGldGtYAAGQcGdmAAShXPYTn4WAsAIoibTIhtmF3SiflAegK2sPwBx4P0jhXUAwJHAtwwiEg53DZhE2wl1cPjLl6CrEhrgoVNYH1FcRPXLc9wPb4-mCWBT3PPxL1Ya9b3vR9nyCV93y-X9-0AlBgOAMCdXubxYNYeDOmQtCMMNYAFNjPDgA01N00zai6ItWiDhoBik00tMM1gDiuOsVhWEzXB6AE7ghIDU5ROTFNKFkkgIqUr0MDCItQAoOBEDnVBtNarTQF3Bgq2IihKOBXTErXTcd33T5jOPMzYDPC8rxvO8HyfF830-b9gD-ACgMwLzwOuSC-LgxCUPQzDwpjBqrBi6qEsDS06Pu7L6FgQFmNI8jwQAfi4niPD45BONAQhWFQIISrKkSxLzCTcCrfLCtUhggnRfAO1AQFxyLZBQEfbjWCwCMoy1eNmFwMniVUkIOkQccgj6nsiooHVriCEaxqe0B9Kmoyj1M8ylusla7PWxzNpcna3P20Cjt8mCzqCi7Qqwm643SOnOUZx7TmS+isG1hntJypGCo5YrBLo-0RIAYWufAasR97AWjHDNfxwFUEbFrqC8Qbay7G12lAKnZMTcm-EUItaYYnWatJqtPdG8a9MmwyZsFk8Fos3VltstaHKcrbXL2jyDu8iCoP8wLgsusL6s94AWYLHU9aS81W7Zvxd1dr7WIo-7uN4vxQabvDoZt4TxtAB2ORtKMXY+on6GUe64rqjW8Oxn3mFq1rcADycSGDhEw7HSPPZj8c4-p8dL7JlPuYqvnM8PEyc8WyyC9W+yNucttXa7lCSHR8idJWAVzohSuhPHULcARtz8OAVgAAxVAjRtKD3BB3Z6Bxu46hQegzBQRsHsX7sRMhw9AbA3HtvHUJUAC+1trS2k5FvD2eE7ZwjWAIPshNfR0Vdn1E+ZCAaj2QIoc8-YCzD29KAJilCfrMGoRI0AjC6GcIYTwZhpVeBgG4Y4PwWBgFy3DGEPECAK4YEUDUAm1hCCoFYBYUAsAACOAgiBdHPt7X2FBEB6DAALEygJQlIlqBhOExBkCIlwKgYAqE3L+MJCMVgmxnjWOUF2aJNpkA8C7BwHI7QliwC4msLG4xuL-lQDQfAj5gRpGQA6VK7QSoFKwFHZAXE4FekqcInpyBdyaEUPIxRLFlFcQkNoWQFozgiHUZRNpPCsCOI+lxDc+BcAADUupuz6SvDZHQdkfV3J0xZ+TlmuMghErpEAmgYAAKLXJCPjfZbtwD3KebCF5HElndh9K2VA+Yj5ZlAL0G8DgQWKDzJ0dRoBKlLGgI+REXgOhT0zFgR2QRN5cTArgbFWV4A9g5B4C4ABVa0agIomnkOaQEaAOhZS4h+Blm8iWO1JRS9oVKYw0vNE0H2XEOLwpNGDCGQRaV0TVDQX4rUewdlXNuKeMldwRGKV4YEHA1SGg-HvXcrwNyhFeJRSiPpzS7nkVizecLKmGpqJqjA6N6DnLoha7GrKso2tAHa1gDrHICAwC6g4bqBVYEYfC71oQg19XkdKqM4bbVRqYSwsMqrIgEA1VqmJFBdXgn1dgCJxrTWCIOFaz1lToDIFfJQCgfqGAlQOPSn21q3mgBZc2wlxKj4WqXO6n22UAKdCEMW3tBxK3VqoH65xiIm02l3IO4dDbAyMMlQcFd3EV7cPTQARSEJ4xg7KnY0EgG6uSNBmAfidsgUgaoADWXFgz0HBfQH2kAFnRpDWWMNEbx0PCoB+2NT5CBcTjV639NaXW6KtKmtVGbYAOu1TmvVrx3T0CLWal6HICWZgjah4E4LMz6qFsADgTrjUOo5b8ulHqcOtvbYyzM7KSXkspdSntiUL6QEgn2udC7YAjo4wcIEcSsB4dndlPDpHp2KD49Gtdq71G2M3c49ou7YD7poIem0x7T01IvVem9yB70hifQwV976l2fp9mBqtf7hqWcAzQYDYcnzxtw5ESD1teiRD7E41S9wInkCoLQbKXhgupRA-QSAoMuUYB5RqDDpaGLwyud8yyAWQi7h-PAJC2AKMdjnCesL1BUomuTXoqmXHEBgp8zIs4qUMBBZK9lceFAqvQQcH4OpyAWPcupYlusaVishbESPIGvTQCaCXRipM+KkLal8BgcR43XmTaXb0QmwnrO7hm8N1KBMwxlvigNg4KrOnAlEco+F4xKmaAE4GQM53Xq7lkHJwMG38Y7bSqgCNU2EygAuKAWQQ5UAAGpQf3Ye4GVZIJFuxbUP1RQe3YCrlQNuN7a7R0KJrSNq7lSYeggYrFqQIghkxykhj7H4WSCVOR5qyEaoNQvcp09qq2U7tLsxxx1nGVsrncu2xUAoOqfNeBNOHBnOwWEy+1gH7t2QcA5FyFsXyiQfg+zFh+bvRFvg8hw9gncPKWqs1wthiSOcepVR+jyXuiHtnZTgLii13acW++mxPXgZIBdU6EzYR8OIqnM9pT5HZDfuS6S3N03WB5dY551pIZb3bfqJ0dbSr3HvOQRka1BwQQmshd3Mjri-uYygwAApVrRL4C44NIaipLWHQEImN1u1dHBXcq5e1+9YzGPuK9iciAD6uOn4vmDo4u0HhTBxkcKfR72ijJKOJz+gOgWAKDdyzs3iM0Alb5rtDtmeXwXEexCAWeVngPY331621gXw9Bc+u93Bl2AefUrt-kejYFXhFAEchV-0AMLFNQBgRgC410do0PsG8m9dx2kld9ssRDYX8WsPdr9s879ECC9Xdo1dFw0uQMAGY+p+MBtb979qdH9nln8H94Nkcyt+Uv0qNuAoNeBjgmgkUYkBs40FMn9EDOCv0FMGtuDzQjssxzRiCBC6IN8spJVGESpdggA)

**Comment by guest271314** [comment]
TypeScript is lagging behind JavaScript in the implementation of resizable `ArrayBuffer`. See the PR https://github.com/microsoft/TypeScript/pull/58573#issuecomment-2254718432 from the comment/reference 

https://github.com/guest271314/native-messaging-typescript/blob/cd0d2fc81fd0e7bac88d6f374c67688b7e3d25e9/nm_typescript.ts#L9C27-L9C154

```
  * /// <reference types="https://raw.githubusercontent.com/microsoft/TypeScript/eeffd209154b122d4b9d0eaca44526a2784073ae/src/lib/es2024.arraybuffer.d.ts" />
```

The TypeScript playground doesn't recognize the embedded interface. Neither does `deno check` https://www.reddit.com/r/Deno/comments/1e6hyeh/comment/lffpz70/

> You might want to look into the behaviour of deno check. The output is full of errors when we include the declaration in the file, but not yet defined in the TypeScript compiler that checks the file. deno executes the file just fine. Download this file https://raw.githubusercontent.com/guest271314/NativeMessagingHosts/main/nm_typescript.ts and run deno check locally. First error
```
error: TS2740 [ERROR]: Type 'ArrayBuffer' is missing the following properties from type 'ArrayBuffer': maxByteLength, resizable, resize, detached, and 2 more.
const buffer: ArrayBuffer = new ArrayBuffer(0, { maxByteLength: 1024 ** 2 });
```

The Deno folks banned me so I can't file an issue over there in denoland for `check` failing to recognize the embedded interface. From what I gather Deno uses a `tsc` that doesn't stay up to date with the JavaScript implementation in Deno. The same must be true for Bun and Node.js.

The code runs in `deno`, `bun`, and `node`, anyway.

The `.js` source does not produce any errors for `deno check`, as well as `deno lint`, after I fixed what those commands output.

So it's an internal TypeScript issue, that is observable in TypeScript and downstream for programs that use "stable" TypeScript.

**Comment by salmin89** [comment]
I see. 

Which minimum node version does it run in? 

Got any unit tests or plan on setting them up?

**Comment by guest271314** [comment]
I'm running v23.0.0-nightly202407272d1b4a8cf7.

I've got a test I've been running that I included the TypeScript version in https://gist.github.com/guest271314/7d2118bd395bf1e3475b70b0187910f2.

`node` is slower than `deno`, which is slower than `bun` running the same `.ts` file.

From a few seconds ago

```
0	'nm_qjs'	0.1102999999821186
1	'nm_tjs'	0.15969999998807907
2	'nm_bun'	0.2365
3	'nm_deno'	0.2684000000059605
4	'nm_typescript'	0.31259999999403953
5	'nm_nodejs'	0.36440000000596046
6	'nm_spidermonkey'	0.39559999999403955
7	'nm_d8'	0.4537000000178814
```

**Comment by salmin89** [comment]
How are you testing those?
Got a script you can share?

**Comment by guest271314** [comment]
In DevTools Sources => Snippets in my custom new tab extension. For each host manifest I include the extension URL of my new tab extension.

`test_stdin.js`
```
var runtimes = new Map([
  ["nm_nodejs", 0],
  ["nm_deno", 0],
  ["nm_bun", 0],
  ["nm_tjs", 0],
  ["nm_qjs", 0],
  ["nm_spidermonkey", 0],
  ["nm_d8", 0],
  ["nm_typescript", 0]
]);
for (const [runtime] of runtimes) {
  try {
    const {
      resolve,
      reject,
      promise
    } = Promise.withResolvers();
    const now = performance.now();
    const port = chrome.runtime.connectNative(runtime);
    port.onMessage.addListener((message) => {
      runtimes.set(runtime, (performance.now() - now) / 1000);
      port.disconnect();
      resolve();
    });
    port.onDisconnect.addListener(() => reject(chrome.runtime.lastError));
    port.postMessage(new Array(209715));
    if (runtime === "nm_spidermonkey") {
      port.postMessage("\r\n\r\n");
    }
    await promise;
  } catch (e) {
    console.log(e, runtime);
    continue;
  }
}
var sorted = [...runtimes].sort(([, a], [, b]) => a < b ? -1 : a === b ? 0 : 1);
console.table(sorted);
```

![Screenshot_2024-07-30_07-02-54](https://github.com/user-attachments/assets/40c9b6b6-9db6-4179-8ac6-62eb3c229a96)

**Comment by salmin89** [comment]
cool. Would it be possible test by making a shell-script (or any testing framework of choice) - to replicate how chrome launches these hosts? I haven't figured out how to do it myself.
If you ever plan on making such script, please share it :)

**Comment by salmin89** [comment]
Ok I'm managed to complete a test script myself. This could be used similarly to your extension script code. I'll make a gist out of it once I figure out how I want to package it

**Comment by guest271314** [comment]
>  to replicate how chrome launches these hosts? I haven't figured out how to do it myself.

What do you mean by how Chrome launches the hosts? You can read the arguments to the script in the script. See the `args` variable here https://github.com/guest271314/NativeMessagingHosts/blob/main/nm_host.js.

If you mean implement the Native Messaging protocol, I've done it. I'll have to go through my archives to locate the code.

Basically just implement the Native Messaging protocol https://developer.chrome.com/docs/extensions/mv3/nativeMessaging/#native-messaging-host-protocol between discrete applications/shell scripts/programs/runtimes. 

It's similar to HTTP `Transfer-Encoding: chunked`. Length of message, followed by message. See https://github.com/guest271314/direct-sockets-http-ws-server/blob/main/assets/script.js#L307-L361.

Other experiments implementing I/O between browser and arbitrary application using files https://github.com/guest271314/fs.

**Comment by salmin89** [comment]
> If you mean implement the Native Messaging protocol, I've done it. I'll have to go through my archives to locate the code.

This is what I meant. But I managed to get it working myself. So now I can run integration tests against my host if I want to. 

However, this is not relevant to the issue submitted so I'll take this elsewhere.

**Comment by guest271314** [comment]
@salmin89 https://github.com/guest271314/NativeMessagingHosts/discussions
